addpath(pwd,strcat(pwd,'\DataSet_1'),...
            strcat(pwd,'\DataSet_2'),...
            strcat(pwd,'\Filtering\bilateral_filter\Bilateral Filtering'),...
            strcat(pwd,'\Learning\adaboost'),...
            strcat(pwd,'\Learning\adaboost\uz_thesis'),...
            strcat(pwd,'\Classification\libsvm-3.11\matlab'),...
            strcat(pwd,'\Classification\pls_toolbox'),...
            strcat(pwd,'\RoadTracking'),...
            strcat(pwd,'\RoadTracking\DrawLine'),...
            strcat(pwd,'\Texture'),...
            strcat(pwd,'\meanshift\bin\edison_m2007a_vc2005'),...
            strcat(pwd,'\scripts'),...
            strcat(pwd,'\utils'),...
            strcat(pwd,'\Filtering\Steerable_Filters'),...
            strcat(pwd,'\SORM'),...
            strcat(pwd,'\ACE'),...
            strcat(pwd,'\Classification'));