function createcontour(xdata1, zdata1, Parent1)
%CREATECONTOUR(XDATA1,ZDATA1,PARENT1)
%  XDATA1:  contour x
%  ZDATA1:  contour z
%  PARENT1:  contour parent

%  Auto-generated by MATLAB on 17-Oct-2012 10:45:36

% Create contour
contour(xdata1,xdata1,zdata1,'ShowText','on','LineWidth',2,'Fill','on',...
    'Parent',Parent1);

